// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: course.sql

package db

import (
	"context"
	"database/sql"
)

const createCourse = `-- name: CreateCourse :one
INSERT INTO courses (
    name, 
    faculty, 
    department, 
    level, 
    course_code
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, name, faculty, department, level, course_code, num_of_lectures_per_semester, active_lecturer_id
`

type CreateCourseParams struct {
	Name       string `json:"name"`
	Faculty    string `json:"faculty"`
	Department string `json:"department"`
	Level      string `json:"level"`
	CourseCode string `json:"course_code"`
}

func (q *Queries) CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error) {
	row := q.queryRow(ctx, q.createCourseStmt, createCourse,
		arg.Name,
		arg.Faculty,
		arg.Department,
		arg.Level,
		arg.CourseCode,
	)
	var i Course
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Faculty,
		&i.Department,
		&i.Level,
		&i.CourseCode,
		&i.NumOfLecturesPerSemester,
		&i.ActiveLecturerID,
	)
	return i, err
}

const dropCourse = `-- name: DropCourse :execresult
DELETE FROM course_registered_students
WHERE course_code = $1 AND student_id = $2
`

type DropCourseParams struct {
	CourseCode string `json:"course_code"`
	StudentID  int64  `json:"student_id"`
}

func (q *Queries) DropCourse(ctx context.Context, arg DropCourseParams) (sql.Result, error) {
	return q.exec(ctx, q.dropCourseStmt, dropCourse, arg.CourseCode, arg.StudentID)
}

const getCourseFiltered = `-- name: GetCourseFiltered :many
SELECT id, name, faculty, department, level, course_code, num_of_lectures_per_semester, active_lecturer_id FROM courses
WHERE faculty = $1 AND department = $2 AND level = $3
`

type GetCourseFilteredParams struct {
	Faculty    string `json:"faculty"`
	Department string `json:"department"`
	Level      string `json:"level"`
}

func (q *Queries) GetCourseFiltered(ctx context.Context, arg GetCourseFilteredParams) ([]Course, error) {
	rows, err := q.query(ctx, q.getCourseFilteredStmt, getCourseFiltered, arg.Faculty, arg.Department, arg.Level)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Course{}
	for rows.Next() {
		var i Course
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Faculty,
			&i.Department,
			&i.Level,
			&i.CourseCode,
			&i.NumOfLecturesPerSemester,
			&i.ActiveLecturerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerCourse = `-- name: RegisterCourse :exec
INSERT INTO course_registered_students (
    course_code,
    student_id
) VALUES (
    $1, $2
)
`

type RegisterCourseParams struct {
	CourseCode string `json:"course_code"`
	StudentID  int64  `json:"student_id"`
}

func (q *Queries) RegisterCourse(ctx context.Context, arg RegisterCourseParams) error {
	_, err := q.exec(ctx, q.registerCourseStmt, registerCourse, arg.CourseCode, arg.StudentID)
	return err
}
