// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"database/sql"
	"time"
)

type Course struct {
	ID                       int64  `json:"id"`
	Name                     string `json:"name"`
	Faculty                  string `json:"faculty"`
	Department               string `json:"department"`
	Level                    string `json:"level"`
	CourseCode               string `json:"course_code"`
	NumOfLecturesPerSemester int32  `json:"num_of_lectures_per_semester"`
	LecturerAttendedCount    int32  `json:"lecturer_attended_count"`
	ActiveLecturerID         int64  `json:"active_lecturer_id"`
}

type CourseLecturer struct {
	CourseCode   string       `json:"course_code"`
	LecturerID   int64        `json:"lecturer_id"`
	Availability int32        `json:"availability"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}

type CourseStudent struct {
	CourseCode           string       `json:"course_code"`
	StudentID            int64        `json:"student_id"`
	AttendedLectureCount int32        `json:"attended_lecture_count"`
	UpdatedAt            sql.NullTime `json:"updated_at"`
}

type LectureAttendance struct {
	SessionID      int64     `json:"session_id"`
	StudentID      int64     `json:"student_id"`
	AttendanceTime time.Time `json:"attendance_time"`
	Attended       bool      `json:"attended"`
	CreatedAt      time.Time `json:"created_at"`
}

type LectureSession struct {
	ID          int64     `json:"id"`
	CourseCode  string    `json:"course_code"`
	LecturerID  int64     `json:"lecturer_id"`
	SessionDate time.Time `json:"session_date"`
	CreatedAt   time.Time `json:"created_at"`
}

type Lecturer struct {
	ID                      int64        `json:"id"`
	UserID                  int64        `json:"user_id"`
	Courses                 []string     `json:"courses"`
	CoursesActivelyTeaching []string     `json:"courses_actively_teaching"`
	UpdatedAt               sql.NullTime `json:"updated_at"`
	WeightedAvailability    float64      `json:"weighted_availability"`
}

type Student struct {
	ID        int64        `json:"id"`
	UserID    int64        `json:"user_id"`
	Courses   []string     `json:"courses"`
	UpdatedAt sql.NullTime `json:"updated_at"`
}

type User struct {
	ID              int64        `json:"id"`
	FullName        string       `json:"full_name"`
	Roles           []string     `json:"roles"`
	CardUid         string       `json:"card_uid"`
	Enrolled        bool         `json:"enrolled"`
	Email           string       `json:"email"`
	SchID           string       `json:"sch_id"`
	HashedPassword  string       `json:"hashed_password"`
	PasswordChanged bool         `json:"password_changed"`
	UpdatedAt       sql.NullTime `json:"updated_at"`
	CreatedAt       time.Time    `json:"created_at"`
}
