// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateEligibility(ctx context.Context, arg CreateEligibilityParams) (Eligibility, error)
	CreateStudent(ctx context.Context, arg CreateStudentParams) (Student, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteEligibility(ctx context.Context, arg DeleteEligibilityParams) error
	DeleteStudent(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) (sql.Result, error)
	GetEligibility(ctx context.Context, arg GetEligibilityParams) (Eligibility, error)
	GetStudentByID(ctx context.Context, id int64) (Student, error)
	GetStudentByUserID(ctx context.Context, userID int64) (Student, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	ListEligibilityForStudent(ctx context.Context, studentID int64) ([]Eligibility, error)
	ListStudents(ctx context.Context) ([]Student, error)
	UpdateEligibility(ctx context.Context, arg UpdateEligibilityParams) (Eligibility, error)
	UpdateStudentBiometric(ctx context.Context, arg UpdateStudentBiometricParams) (Student, error)
	UpdateStudentCourses(ctx context.Context, arg UpdateStudentCoursesParams) (Student, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
