// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	AssignLecturerToCourse(ctx context.Context, arg AssignLecturerToCourseParams) error
	BatchGetEligibilityMetaData(ctx context.Context, studentids []int64) ([]BatchGetEligibilityMetaDataRow, error)
	CreateCourse(ctx context.Context, arg CreateCourseParams) (Course, error)
	CreateLectureAttendance(ctx context.Context, arg CreateLectureAttendanceParams) error
	CreateLectureSession(ctx context.Context, arg CreateLectureSessionParams) (int64, error)
	CreateLecturer(ctx context.Context, userID int64) (Lecturer, error)
	CreateStudent(ctx context.Context, userID int64) (Student, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCourse(ctx context.Context, courseCode string) (sql.Result, error)
	DeleteLecturer(ctx context.Context, id int64) (sql.Result, error)
	DeleteStudent(ctx context.Context, id int64) (sql.Result, error)
	DeleteUser(ctx context.Context, id int64) (sql.Result, error)
	DropCourse(ctx context.Context, arg DropCourseParams) (sql.Result, error)
	GetAllStudentsEligibilityForCourse(ctx context.Context, courseCode string) ([]GetAllStudentsEligibilityForCourseRow, error)
	GetCourse(ctx context.Context, courseCode string) (Course, error)
	GetCourseMetaData(ctx context.Context, courseCode string) (GetCourseMetaDataRow, error)
	GetCoursesFiltered(ctx context.Context, arg GetCoursesFilteredParams) ([]Course, error)
	GetLectureAttendance(ctx context.Context, sessionID int64) ([]LectureAttendance, error)
	GetLectureSession(ctx context.Context, courseCode string) ([]LectureSession, error)
	GetLecturerAvailabilityForAllCourses(ctx context.Context, lecturerID int64) ([]GetLecturerAvailabilityForAllCoursesRow, error)
	GetLecturerByID(ctx context.Context, id int64) (Lecturer, error)
	GetLecturerByUserID(ctx context.Context, userID int64) (Lecturer, error)
	GetStudentByID(ctx context.Context, id int64) (Student, error)
	GetStudentByUserID(ctx context.Context, userID int64) (Student, error)
	GetStudentEligibilityForAllCourses(ctx context.Context, studentID int64) ([]GetStudentEligibilityForAllCoursesRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	RegisterCourse(ctx context.Context, arg RegisterCourseParams) error
	RemoveActiveLecturer(ctx context.Context, arg RemoveActiveLecturerParams) error
	SetActiveLecturer(ctx context.Context, arg SetActiveLecturerParams) error
	UnassignLecturerFromCourse(ctx context.Context, arg UnassignLecturerFromCourseParams) (sql.Result, error)
	UpdateCourseNumberOfLecturesPerSemester(ctx context.Context, arg UpdateCourseNumberOfLecturesPerSemesterParams) error
	UpdateLecturerAttendedCount(ctx context.Context, courseCode string) error
	UpdateLecturerCourses(ctx context.Context, arg UpdateLecturerCoursesParams) (Lecturer, error)
	UpdateStudentCourses(ctx context.Context, arg UpdateStudentCoursesParams) (Student, error)
	UpdateStudentStudentEligibility(ctx context.Context, arg UpdateStudentStudentEligibilityParams) error
	UpdateUserEmail(ctx context.Context, arg UpdateUserEmailParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (User, error)
}

var _ Querier = (*Queries)(nil)
